name: Squid Proxy Service
on: [push, workflow_dispatch]

jobs:
  # Label of the container job
  test-with-proxy:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    # Service containers to run with `test-with-proxy`
    services:
      # Label used to access the service container
      squid:
        # Docker Hub image
        image: ubuntu/squid
        #
        ports:
          # Maps tcp port 3128 on the host to the same port in the service container
          - 3128:3128

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: rockcarver/frodo
          ref: "v0.9.2-1"

      - name: 'cat package.json'
        run: cat ./package.json

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies and install frodo globally
        run: |
          npm ci
          npm i -g

      #
      # Run tests.
      #
      - name: Version Test
        run: |
          frodo -v

      - name: Direct Tests
        env:
          FIDC_TENANT_URL: ${{ secrets.FIDC_TENANT_URL }}
          FIDC_TENANT_ADMIN_USERNAME: ${{ secrets.FIDC_TENANT_ADMIN_USERNAME }}
          FIDC_TENANT_ADMIN_PASSWORD: ${{ secrets.FIDC_TENANT_ADMIN_PASSWORD }}
        run: |
          frodo conn add "$FIDC_TENANT_URL" "$FIDC_TENANT_ADMIN_USERNAME" "$FIDC_TENANT_ADMIN_PASSWORD"
          frodo info "$FIDC_TENANT_URL"

      - name: Proxy Tests
        env:
          HTTPS_PROXY: "http://127.0.0.1:3128"
          FIDC_TENANT_URL: ${{ secrets.FIDC_TENANT_URL }}
          FIDC_TENANT_ADMIN_USERNAME: ${{ secrets.FIDC_TENANT_ADMIN_USERNAME }}
          FIDC_TENANT_ADMIN_PASSWORD: ${{ secrets.FIDC_TENANT_ADMIN_PASSWORD }}
        run: |
          frodo conn add "$FIDC_TENANT_URL" "$FIDC_TENANT_ADMIN_USERNAME" "$FIDC_TENANT_ADMIN_PASSWORD"
          frodo info "$FIDC_TENANT_URL"
